### ISSUE TITLE
USER STORY: Set up front-end workspace

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#1]
EPIC: Project setup

As a **developer** I can **set up a new workspace for front-end** so that **I can start working on my project.**

## Acceptance Criteria
- A repository is in Github
- An IDE to work in
- readme and testing files

## Tasks
- [x]  Task 1: Create a github repository with initial README and TESTING files
- [x]  Task 3: Install React Framework
- [x]  Task 4: Install React Bootstrap
