### ISSUE TITLE
USER STORY: Validate each page and app for front-end

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#11]
EPIC: Documentation

As a **developer**, I can **validate each page and app for front-end** so that **I know that the code adheres to best practices.**

## Acceptance Criteria
- Acceptance Criteria 1: Html pages are validated with no critical issues
- Acceptance Criteria 2: CSS pages are validated with no critical issues
- Acceptance Criteria 3: JS pages are validated with no critical issues

## Tasks
- [x]  Task 1: Check each html page against W3C html validator
- [x]  Task 2: Check each css file against W3C CSS validator
- [x]  Task 3: Check each JS file against JSlinter validator
- [x]  Task 4: Document any major validation errors in the TESTING.md
