### ISSUE TITLE
USER STORY: Login to & logout of the website

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#13]
EPIC: User registration

As a **site user** I can **login to & logout of the website** so that **I can access functionality for logged in users.**

## Acceptance Criteria
- Acceptance Criteria 1: log in button is visible in the navigation bar and renders the login component upon click
- Acceptance Criteria 2: the user can login using their username and password
- Acceptance Criteria 3: the user is taken to the home page upon successful log in
- Acceptance Criteria 4: the Avatar is visible in the nav bar indicating that the user is logged in
- Acceptance Criteria 5: logout button is visible in the navbar upon successful log in

## Tasks
- [x]  Task 1: display error messages if login input is incorrect
- [x]  Task 2: create a redirect route to homepage
- [x]  Task 3: display user’s nane in the navbar (or a profile image - optional)
- [x]  Task 4: set up redirection to the home page after logging in/out.
