### ISSUE TITLE
USER STORY: View the navbar from every page

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#14]
EPIC: User navigation

As a **site user** I can **view the navbar from every page** so that **I can navigate easily between pages.**

## Acceptance Criteria
- Acceptance Criteria 1: The logo/website name is visible
- Acceptance Criteria 2: The main navigation menu is present

## Tasks
- [x]  Task 1: create the navbar component for the website
- [x]  Task 2: add the logo/website name to the header
- [x]  Task 3: set up navigation links for registered users:
    - [x]  Home page
    - [x]  Post an Artwork
    - [x]  Logout
    - [x]  Create a listing
    - [x]  Profile Avatar (not priority)
    - [x]  Saved/Bookmarked listings (not priority)
- [x]  Task 4: set up navigation links for not registered users:
    - [x]  Register
    - [x]  Login
