### ISSUE TITLE
USER STORY: Edit the artwork post

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#17]
EPIC: Artwork functionality

As a **site user** I can **edit the artwork post** so that I can **show the most up to date information**.

## Acceptance Criteria
- Acceptance Criteria 1: an edit icon visible in the detailed post page
- Acceptance Criteria 2: a submit button is visible to update the post

## Tasks
- [x]  Task 1: write a code for favicon to indicate an action
- [x]  Task 2: populate the form with pre-existing data
- [x]  Task 3: code submit button functionality to override pre-existing data
