### ISSUE TITLE
USER STORY: access a detailed artwork post

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#19]
EPIC: Artwork functionality

As a **site user** I can **access a detailed artwork post** so that **I can read more about it.**

## Acceptance Criteria
- Acceptance Criteria 1: display detailed information about the listed artwork

## Tasks
- [x]  Task 1: create artwork post detail component
- [x]  Task 2: display the artwork’s image
- [x]  Task 2: display the artwork’s description, price, style, location, payment method
