### ISSUE TITLE
USER STORY: Front-end deployment

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#2]
EPIC: Deployment 

As a **developer** I can **deploy the front-end repository to Heroku** so that **it is accessible online.**

## Acceptance Criteria
* Acceptance Criteria 1: The project is deployed

## Tasks
- [x]  Task 1:  Push the project to Github repository
- [x]  Task 2: Connect Github repo to Heroku
- [x]  Task 3:Deploy to Heroku
- [x]  Task 4: Check the deployed front-end app is working
