### ISSUE TITLE
USER STORY: Make a bid for the artwork

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#20]
EPIC: Bid functionality

As a **buyer** I can **make a bid the artwork** so that **I can buy it.** 

## Acceptance Criteria
- Acceptance Criteria 1: a form for bid input below detailed artwork information
- Acceptance Criteria 2: show the bid's status

## Tasks
- [x]  Task 1: populate a bid form with currency input specification
- [x]  Task 2: display the bid once submitted
- [x]  Task 3: display the status of the bid: pending/approved/rejected/sold
- [x]  Task 4: display the date when the bid was submitted and the name of the bidder
