### ISSUE TITLE
USER STORY: review pending bids

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#22]
EPIC: Bidfunctionality

As a **seller** I can **review pending bids** so that **I can decide which seller to sell the artwork to.**

## Acceptance Criteria
- Acceptance Criteria 1: Display any existing bids for the listing in the artwork detailed view
- Acceptance Criteria 2: Display Accept/Reject/Sold buttons

## Tasks
- [x]  Task 1: code a button for “Accept” bid
- [x]  Task 2: code a button for “Reject” bid
- [x]  Task 3: code a button for “Sold” bid
