### ISSUE TITLE
USER STORY: update my profile

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#25]
EPIC: Profile functionality

As a **logged in user** I can **update my profile** so that **I can keep it up-to-date with most relevant information.** 

## Acceptance Criteria
- Acceptance Criteria 1: have a profile page
- Acceptance Criteria 2: have a profile avatar visible in the navbar and the profile component
- Acceptance Criteria 3: have an upload image in the profile page

## Tasks
- [x]  Task 1: Create a profile component
- [x]  Task 2: write a code for form to include the following fields:
    - [x]  Location
    - [x]  Profile image
    - [x]  Name
    - [x]  Contact
    - [x] Styles
    - [x] Techniques
    - [x] Influences
    - [x] Collaborations
    - [x] Portfolio url
- [x]  Task 3: create and style the Avatar component
- [x]  Task 4: set a default profile image to show automatically
- [x]  Task 5: code a submit button
