### ISSUE TITLE
USER STORY: search for artworks by keyword or filter by style/type/artwork

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#27]
EPIC: Artwork functionality

As a **site user** I can **search for artworks by keyword or filter by category/style** so that **I can find listings relevant to my interests.**

## Acceptance Criteria
- Acceptance Criteria 1: a search bar is present on the homepage and listing pages
- Acceptance Criteria 2: users can input keywords  into the search bar.
- Acceptance Criteria 3: the search function displays only listings matching the entered keywords.
- Acceptance Criteria 4: display a "No results found" message if keywords don’t match the query.

## Tasks
- [x]  Task 1: add a search bar component to the homepage and listing pages
- [x]  Task 2: implement a query to filter listings by the input keyword
- [x]   Task 3: implement a query to filter listings by style/type of artwork
- [x]  Task 4: display filtered results on the page
- [x]  Task 5: display a "No results found" message if no listings found
