### ISSUE TITLE
USER STORY: see notification messages

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#28]
EPIC: User nofications

As a **site user**, I can **see notification messages** so that **I know that my action was successful/completed.** 

## Acceptance Criteria
- Acceptance Criteria 1: the message is visible upon the action is completed
- Acceptance Criteria 2: the message times out authomatically

## Tasks
- [x]  Task 1: find a message tool online
- [x]  Task 2: code the functionality for each component
- [x]  Task 3: style it to be compatible with website design
