### ISSUE TITLE
USER STORIES: see top selling displayed on each page

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#29]
EPIC: Artwork functionality

As a **site user** I can **see top selling profiles displayed on each page** so that I **can view their profiles.**

## Acceptance Criteria
- Acceptance Criteria 1: a component is placed to the side/top of the page
- Acceptance Criteria 2: user profile avatars are visible
- Acceptance Criteria 3: a left/right/up/down arrow is present to navigate between profiles

## Tasks
- [x]  Task 1: create a most selling profile component
- [x]  Task 2: add profile avatar component
- [x]  Task 3: write code for arrow navigation
