### ISSUE TITLE
USER STORY: Add a favicon

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#3]
EPIC: Project setup

As a **developer** I can **add a favicon** so that **the website renders appropriate image in the browser.** 

## Acceptance Criteria
* Acceptance Criteria 1: favicon is visible in the browser

## Tasks
- [x]  Task 1: choose a favicon
- [x]  Task 2: save favicon in Assets folder
- [x]  Task 3: implement favicon in the code
