### ISSUE TITLE
USER STORY: submit a contact form

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#30]
EPIC: Contact functionality

As a **site user** I can **submit a contact form to site admins** so that **I can report any issues with the website.** 

## Acceptance Criteria
* Acceptance Criteria 1: contact form is visible on the website page
* Acceptance Criteria 2: contact link is present in the navigation bar
* Acceptance Criteria 3: Submit button is visible

## Tasks
- [ ] Task 1: write contact component
- [ ] Task 2: write code to display name, email, body fields in the form
- [ ] Task 3: code a submit button 
- [ ] Task 4: apply css to style the component 
- [ ] Task 5:
