### ISSUE TITLE
USER STORY: My Bids page

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#32]
EPIC: Bid functionality

As a **site user**, I can **see the My bids tab** so that **I can access and see all of the bids I submitted.**

## Acceptance Criteria
- Acceptance Criteria 1: My Bids page is visible in the navbar.
- Acceptance Criteria 3: List all bids on a page showing the status

## Tasks
- [ ] Task 1: create a component to display artworks that have been bid on
- [ ] Task 2: add a route to the page
- [ ] Task 3: display the status of the bid: pending/approved/rejected/sold
- [ ] Task 4: display the date when the bid was submitted and the name of the bidder
