### ISSUE TITLE
USER STORY: Apply design of choice

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#5]
EPIC 6: Website design

As a **developer** I can **apply design of choice** so that **the website is visually appealing and represents the purpose.**

## Acceptance Criteria
* Acceptance Criteria 1: Design layout is implemented
* Acceptance Criteria 2: Font and colour scheme are implemented

## Tasks
- [x] Task 1: Choose React Bootstrap design style 
- [x] Task 2: Choose font 
- [x] Task 3: Choose colour palette
