### ISSUE TITLE
USER STORY: Carry out website design improvement

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#6]
EPIC: Website design

As a **developer**, I can **carry out website design improvement** so that **I know the project adheres to the principles of UX/UI design.**

## Acceptance Criteria
- Acceptance Criteria 1: The design follows best UX/UI practices ensuring good user experience.

## Tasks
- [x] Task 1: Check the website against the lighthouse
- [x] Task 2: Check the website against the WAVE and other accessibility tools
- [x] Task 2: Perform usability testing on mobile, tablet, laptop and browsers
