### ISSUE TITLE
USER STORY: Front-end README 

### ISSUE THREAD

**Issue by laurakond** [laurakond/artly#7]
EPIC: Documentation

As a **developer**, I can **note the website progression in the front-end README** so that **anyone can see the steps and actions taken for the release of the website.**

## Acceptance Criteria
- Acceptance Criteria 1: Readme.md file is updated throughout the progression of the project
- Acceptance Criteria 2: TESTING.md file is updated with any changes and major bugs

## Tasks
- [x]  Task 1: Record project scope and technologies used in the README.md
- [x]  Task 2: Record any resources and tools used for testing, validation and deployment
- [x]  Task 3: Have a section about deployment, cloning and forking the repository
- [x]  Task 4: Include the deployed site’s website in the README.md
- [x]  Task 5: Log design choices and changes in the README.md
- [x]  Task 6: Proofread
